<link rel="icon" type="image/gif" href="Images/logo.png">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="Style/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="Style/style.css">
  <link rel="stylesheet" type="text/css" href="Style/external.css">
  <script src="Scripts/jquery.min.js"></script>
  <script src="Scripts/bootstrap.min.js"></script>
  <script type="text/javascript" src="Scripts/external.js"></script>
 <script type="text/javascript" src="Scripts/jquery-1.3.2.min.js"></script>
 <script type="text/javascript" src="Scripts/script.js"></script>
 <script type="text/javascript" src="Scripts/jquery.js"></script>